# Simple workflow for deploying static content to GitHub Pages
name: AzureStorageStaticHtml

on:
    push:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name alicamlibelstorage --auth-mode key -d '$web' -s ./dist --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "alicamlibel-web-cdn" --name "alicamlibel-web-cdn" --resource-group "alicamlibel-rg"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()